# Generated by Django 3.1.7 on 2021-05-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=51, null=True)),
                ('waiting_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('photos', models.ImageField(upload_to='doc_photo/')),
                ('clinics_photo', models.ImageField(upload_to='photo/')),
                ('date_of_creating_profile', models.DateField()),
                ('price', models.IntegerField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
