# Generated by Django 3.1.7 on 2021-03-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=50000, null=True)),
                ('post_time', models.TimeField()),
                ('post_day', models.CharField(blank=True, choices=[('sat', 'sat'), ('sun', 'sun'), ('mon', 'mon'), ('tues', 'tues'), ('wed', 'wed'), ('thur', 'thur'), ('fri', 'fri')], max_length=5, null=True)),
                ('post_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
