# Generated by Django 3.1.7 on 2021-05-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.TimeField(auto_now=True)),
                ('content', models.TextField(blank=True, max_length=100, null=True)),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to=settings.AUTH_USER_MODEL)),
                ('reply_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='blog.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('post_time', models.TimeField()),
                ('post_day', models.CharField(blank=True, choices=[('sat', 'sat'), ('sun', 'sun'), ('mon', 'mon'), ('tues', 'tues'), ('wed', 'wed'), ('thur', 'thur'), ('fri', 'fri')], max_length=5, null=True)),
                ('post_date', models.DateField()),
                ('post_image', models.ImageField(upload_to='post_image/')),
                ('add_to_favorite', models.ManyToManyField(related_name='user_favorities', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='commented_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.post', to_field='title'),
        ),
    ]
