# Generated by Django 3.1.7 on 2021-03-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_author',
            new_name='author',
        ),
    ]
