# Generated by Django 3.1.7 on 2021-03-08 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_to_favorite',
            field=models.ManyToManyField(related_name='user_favorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
