# Generated by Django 3.1.6 on 2021-02-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speialists', models.CharField(choices=[('جلدية', 'جلدية'), ('اسنان', 'اسنان'), ('نفسي', 'نفسي'), ('اطفال حديثي الولادة', 'اطفال حديثي الولادة'), ('مخ واعصاب', 'مخ واعصاب'), ('عظام', 'عظام'), ('نساء وتوليد', 'نساء وتوليد'), ('انف واذن وحنجرة', 'انف واذن وحنجرة'), ('قلب واوعية دموية', 'قلب واوعية دموية'), ('امراض دم', 'امراض دم'), ('اورام', 'اورام'), ('باطنه', 'باطنه'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('جراحة اطفال', 'جراحة اطفال'), ('جراحة اورام', 'جراحة اورام'), ('جراحة اوعية دموية', 'جراحة اوعية دموية'), ('جراحة تجميل', 'جراحة تجميل'), ('جراحه سمنة ومناظير', 'جراحه سمنة ومناظير')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('desription', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('waiting_time', models.FloatField(blank=True, max_length=5, null=True)),
                ('opening_hours', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('doctor_image', models.ImageField(upload_to='doctor_photo/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_place', to='index.place')),
                ('specialist_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='index.category')),
            ],
        ),
    ]
