# Generated by Django 3.1.6 on 2021-02-15 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('specialist_doctor', models.CharField(blank=True, max_length=1000, null=True)),
                ('desription', models.TextField(blank=True, max_length=5000, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(blank=True, max_length=5, null=True)),
                ('waiting_time', models.FloatField(blank=True, max_length=5, null=True)),
                ('opening_hours', models.IntegerField(blank=True, max_length=3, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=20, null=True)),
                ('doctor_image', models.ImageField(upload_to='doctor_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
