# Generated by Django 3.1.7 on 2021-02-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_profile',
            new_name='doctor_profile_1',
        ),
    ]
