# Generated by Django 3.1.7 on 2021-02-26 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 19, 34, 28, 773610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor_reservation',
            name='time_reservation',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 19, 34, 28, 773610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscribed_mails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 19, 34, 28, 773610, tzinfo=utc)),
        ),
    ]
