# Generated by Django 3.1.6 on 2021-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='opening_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
