# Generated by Django 3.1.7 on 2021-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210226_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_reservation',
            name='date_reservation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor_reservation',
            name='time_reservation',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subscribed_mails',
            name='created',
            field=models.DateField(),
        ),
    ]
