# Generated by Django 3.1.7 on 2021-02-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210227_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_reservation',
            old_name='date_reservation',
            new_name='date_reservation1',
        ),
    ]
