# Generated by Django 3.1.7 on 2021-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
