# Generated by Django 3.1.7 on 2021-03-09 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_doctor_profile_1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_mails',
            name='created',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
