# Generated by Django 3.1.7 on 2021-03-14 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210309_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed_mails',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
